name: Publish

on:
  release:
    types: [created]

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16.x

      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Install dependencies
        run: npm ci

      - name: Webpack
        run: npx webpack
        env:
          NODE_ENV: production

      - name: Copy package
        run: cp ./package.json ./dist/package.json

      - name: Set version
        run: sed -i 's/0.0.0/$RELEASE_VERSION/g' dist/package.json
        env:
          RELEASE_VERSION: ${{ env.RELEASE_VERSION }}

      - run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
